# Generated by Django 4.2.20 on 2025-04-05 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_require_date_of_birth'),
        ('users', '0002_userprofile_total_amount_borrowed_and_more'),
    ]

    operations = [
    ]
